### PR TITLE
F!!: add a way to render github gist

### PR DESCRIPTION
**Pull request by laurentmmeyer**
Hey there, 

As discussed, it would be cool to be able to render github gist. This modification does exactly that.

Thanks for the great work! 🙏

### CODE REVIEW

**Comment by laurentmmeyer** [comment]
You might need to add a gist to one of the ghost post to see it in action.

Edit article > Add HTML > Past embedding script of gist

image

**Comment by styxlab** [comment]
perfect, thanks!

**Comment by styxlab** [comment]
@all-contributors please add @huydhoang for code

**Comment by styxlab** [comment]
@all-contributors please add @laurentmmeyer for code

**Pull request merged**
